name: web_archives
description: Willard Shikami's web links dump
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  async_redux: ^16.0.0
  built_collection: ^5.1.1
  built_value: ^8.1.4
  collection: ^1.15.0
  cupertino_icons: ^1.0.2
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  intl: ^0.17.0
  responsive_builder: ^0.4.3
  cached_network_image: ^3.2.2
  rxdart: ^0.27.3
  http: ^0.13.4
  url_strategy: ^0.2.0
  universal_html: ^2.0.8


dev_dependencies:
  build_runner: ^2.1.7
  built_value_generator: ^8.1.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
  #   - assets/images/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-Heavy.ttf
          weight: 800
